### PR TITLE
make NgGrid host methods public for AOT

### PR DESCRIPTION
**Pull request by jskrzypek**

### CODE REVIEW

**Comment by BTMorton** [comment]
Can you please ditch the _ from the newly public methods, as that designates private. Cheers

**Comment by jskrzypek** [comment]
Sure. I didn't want to introduce too big of a change. I'll do it today.

**Comment by jskrzypek** [comment]
Ah, I've hit a snag with that. There's an `@Output` named `onResize` already: https://github.com/jskrzypek/angular2-grid/blob/4c1564b4efd7649bf9c636b92662ba3ad1f9c1f4/src/directives/NgGrid.ts#L27

Since the host method was previously private I'm going to rename it so the exposed api from the directive doesn't change, I'm thinking `onResizeEvent` is a good option.

Perhaps for clarity and consistency I'll rename all of those methods to be `onXXEvent` so it's clear they have similar behavior.

**Comment by jskrzypek** [comment]
Ah, wait, now I see that the NgGridItem directive has a `public onResizeEvent()`, that could cause confusion...

**Comment by jskrzypek** [comment]
What about naming the methods like `xXEventHandler`?

**Comment by jskrzypek** [comment]
I'll go with the `xXEventHandler` convention for now and push a commit. If you don't like it/have a better idea I'm happy to change it however you want.

**Comment by BTMorton** [comment]
Yup, LGTM

**Pull request merged**
