### PR TITLE
Fixed package json for angular-cli aot build

### PR DESCRIPTION
**Pull request by sconix**
I see that you have made some changes for the build system to support aot, but is there a reason why you haven't released a new version yet?

Well at least here is the only changes I had to made for the current code to compile with angular-cli. Works for both jit and aot build.

### CODE REVIEW

**Comment by BTMorton** [comment]
I've published a new version with aot support and bundles. Closing this, but thanks though

**Comment by sconix** [comment]
Thanks, the PR was more meant for quick fix for other if in need of aot support.

**Comment by sconix** [comment]
I tried the latest version and it does not work out of the box for angular-cli. Its because the module parameter is missing from package.json and typings is pointing to the main instead of aot directory. It would be really nice to get this lib to work with angular-cli like other libs do.

**Comment by BTMorton** [comment]
OK, so I've been looking around and I can't find a reference for the module field. Is it specifically for the compiler-cli aot support? The typings field should be pointed at the typings folder as that's were the typings are generated. FWIW, I tried building the two demo projects with the compiler-cli and they managed to build fine. I don't have any angular-cli projects to test with unfortunately. If someone can create a demo for that it would be incredibly useful!

**Comment by NotBad4U** [comment]
@BTMorton your library seem to doesn't work with the latest angular-cli can you take a look at #179 and #188

**Comment by BTMorton** [comment]
Yes, that's what I'm trying to fix now. I noticed you reference this PR in your issue and that's why I'm trying to establish the reason behind the changes.

**Comment by sconix** [comment]
I havent found info about module field. I suspect that it is only for angular so that main can still point to bundle and module to the angular module which need to be aot compatible nowadays. The typings need to point to aot/ main.d.ts for the module to work though. I have just seen many other libs to be setup so that module/typings point to aot and main to bundle.

**Comment by sconix** [comment]
The lastest version works nicely so thanks!

**Pull request closed without merging**
