### PR TITLE
Upgrade to Angular 6

### PR DESCRIPTION
**Pull request by borgitas21**
- Upgrade to Angular 6
- Update some others dev dependencies.

### CODE REVIEW

**Comment by ThomasSchellenbergNextCentury** [comment]
Hey Borga, thanks for the PR!  I can see that the demo is working, but when I try to use your updated branch in my app, I get the following console error:

```
Error: StaticInjectorError(AppModule)[NgGridItem -> KeyValueDiffers]: 
  StaticInjectorError(Platform: core)[NgGridItem -> KeyValueDiffers]: 
    NullInjectorError: No provider for KeyValueDiffers!
```

Have you seen the same?  Any ideas what I might be doing wrong?  (I'm not using KeyValueDiffers in my app, so this is from angular2-grid.)  Thanks!

**Comment by borgitas21** [comment]
At this point, I haven’t been able to reproduce the error you mentioned above. 

I found an issue that could be related https://stackoverflow.com/a/51629023. 
Could you try to do a fresh installation removing the node_modules folder.

In any case, I will dig into the issue trying to reproduce it.

**Comment by borgitas21** [comment]
@ThomasSchellenbergNextCentury were you able to generate the node_modules folder from scratch? Was the problem fix? I haven't been able to reproduce the error :(

**Comment by borgitas21** [comment]
@ThomasSchellenbergNextCentury Could you let me know the way you are using this branch? I have played with different scenarios and haven't been able to reproduce the error you mentioned above.

**Comment by ThomasSchellenbergNextCentury** [comment]
Hey @borgitas21 ,

Sorry, I fixed my problem and meant to post about it but forgot!

The stackoverflow issue you linked helped a lot.  My problem was due to the way I had imported the dependency into my project included a second node_modules folder.

Thanks for your help and for checking-in!

Thomas

**Comment by borgitas21** [comment]
Great, good to know ;)

**Comment by fmontes** [comment]
Any updated on this?

**Comment by mronus** [comment]
@BTMorton any update on this? This is really a great library; however it is sad that it prevents us from migrating our project from Angular 4 to Angular 6, and only angular2-grid among among 54 libraries that we use for our project has no support for Angular 6. We look forward for any update on this. Thanks in advance.

**Comment by borgitas21** [comment]
@BTMorton are you missing something in this PR? Please let me know if I can help to merge the PR.

**Comment by endlesscadence** [comment]
@BTMorton We have the same issue with this library. It's wonderful and we're using it for quite some time now but it's sad that it's broken with Angular 6. This means that we have to drop the functionality which depends on this library because we have to upgrade to Angular 6 for other reasons. 
If you need help completing this PR please let me know!

**Comment by mronus** [comment]
@BTMorton 's last activity on GitHub was on 31st Aug. I hope he didn't leave the World.

**Comment by borgitas21** [comment]
> @BTMorton 's last activity in GitHub was on 31st Aug. I hope he didn't leave the World.

Hopefully, He is ok :)

**Comment by BTMorton** [comment]
Not dead, just burn out. v3.0.0 with full angular v6 support published.

**Comment by mronus** [comment]
@BTMorton You are the MAN. Thanks a lot.

**Pull request closed without merging**
